name: Cypress E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      # -------------------------
      # DESKTOP RUN
      # -------------------------
      - name: Run desktop tests
        run: npx cypress run --record --config-file cypress.config.ts --tag desktop
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      # -------------------------
      # MOBILE RUN
      # -------------------------
      - name: Run mobile tests
        run: npx cypress run --record --config-file cypress.mobile.config.ts --tag mobile
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}